### ISSUE TITLE
Policer: support NetworkSelector besides PodSelector in Ingress and Egress rules

### ISSUE THREAD

**Issue by Levovar** [nokia/danm-utils#20]
In a traditional K8s NetworkPolicy admins can use Pod, and Namespace selectors to select which Pods should be the targets of Ingress, and Egress policies.
The main design reason behind creating a separate NP API for DANM is to be able to exapnd this with a third kind of selector.
A network selector can be used alone, or in combination with the other selectors to select a Pod. But, besides selecting a Pod it can also further narrow down which exact interface inside the Pod is selected to be the target of a rule.
The default functionality is that all interfaces of a selected Pod are whitelisted when there is no network selector defined for a rule. When there is, only the interface(s) belongig to the selected network(s) are added to the whitelist.

Similarly to Pod and Namespace selectors it should be possible to refer to multiple networks in the same rule defintion. Contrary to the existing selectors thought networks will be selected by their API type and name; because this duplet is already the usual way of how networks are referenced in DANM (attachment definition in Pod, network selector in DANM Services etc.)
Therefore a network selector attribute should be in list format, each entry containing a network type - network name duplet.

Network selectors will be the primary means of being able to selectively micro-segment Pod connections in a multi-interface environment, such as one managed by DANM.

**Comment by Levovar** [comment]
NetworkSelector is now universally supported in addition to PodSelector!
The K8s documentation highlighted selector interaction mechanisms both work (https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-to-and-from-selectors).

When both selectors are defined in the **same** rule for example:
```
spec:
  egress:
  - to:
    - networkSelector:
      - name: poltest
        type: ClusterNetwork
      podSelector:
        matchLabels:
          poltest: to
  ingress:
  - from:
    - networkSelector:
      - name: default
        type: ClusterNetwork
      podSelector:
        matchLabels:
          poltest: from
```
Policer only whitelists the addresses which are matching both selectors. In this case one particular interface belonging to the selected networks inside the Pods selected by the PodSelector:
```
Chain DANM_EGRESS_V4 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.240.1.100
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DANM_INGRESS_V4 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       10.244.2.78          0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

When multiple rules are defined, each separately containing one -or more- selectors like for example:
```
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          poltest: to
    - networkSelector:
      - name: poltest
        type: ClusterNetwork
  ingress:
  - from:
    - podSelector:
        matchLabels:
          poltest: from
    - networkSelector:
      - name: default
        type: ClusterNetwork
```
 we need to whitelist the summary of all the addresses individually selected by the different rules. In this case **all** network addresses belonging to the selected networks **and** all network addresses of the selected Pods:
```
Chain DANM_EGRESS_V4 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.240.1.100
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.244.0.125
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.240.1.101
    0     0 ACCEPT     all  --  *      *       0.0.0.0/0            10.240.1.102
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DANM_INGRESS_V4 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  *      *       10.240.1.101         0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       10.244.2.78          0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       10.244.0.125         0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       10.244.1.144         0.0.0.0/0
    0     0 ACCEPT     all  --  *      *       10.244.3.192         0.0.0.0/0
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```
